### PR TITLE
Fix vote transition role pings

### LINKED ISSUE #28: Vote Role Ping Uses ID Instead of Name
When votes turn into full queues after reaching the minimum number of votes, the resulting 10 mans role ping contains a numeric ID instead of the actual named role.

### PR DESCRIPTION
**Pull request by JoshSanch**
Closes #28 .

### CODE REVIEW

File: src/commands/tenmans.ts [hunk 1]
```diff
@@ -186,7 +186,7 @@ class VoteQueueButtonAction extends VoteQueueAction<ButtonInteraction> {
       });
 
       await queueChannel.send({
-        content: `<@${roleId}> that Radianite must be ours! A queue has been created!`,
+        content: `<@${tenmansRole.name}> that Radianite must be ours! A queue has been created!`,
```
Comment (pattyjogal) [inline src/commands/tenmans.ts]: Change to this syntax: https://stackoverflow.com/questions/58749366/how-do-i-mention-a-role-with-discord-js

**Review by pattyjogal — CHANGES_REQUESTED** [review]

**Review by pattyjogal — APPROVED** [review]
